/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabaniprojesi;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class MusteriEkle extends javax.swing.JFrame {

    /**
     * Creates new form MusteriEkle
     */
    public MusteriEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        musteriAdı = new javax.swing.JLabel();
        MusteriSoyadi = new javax.swing.JLabel();
        adres = new javax.swing.JLabel();
        Talepurun = new javax.swing.JLabel();
        musteriadı = new javax.swing.JTextField();
        musterisoyadı = new javax.swing.JTextField();
        Adres = new javax.swing.JTextField();
        TalepUrun = new javax.swing.JTextField();
        MusteriEkle = new javax.swing.JButton();
        mesajkutusu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        musteriAdı.setText("Müsteri Adı :");

        MusteriSoyadi.setText("Müsteri Soyadı:");

        adres.setText("Adres:");

        Talepurun.setText("Talep Edilen Ürün:");

        musteriadı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musteriadıActionPerformed(evt);
            }
        });

        MusteriEkle.setText("Ekle");
        MusteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriEkleActionPerformed(evt);
            }
        });

        mesajkutusu.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(137, Short.MAX_VALUE)
                        .addComponent(mesajkutusu, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MusteriSoyadi)
                            .addComponent(musteriAdı)
                            .addComponent(adres)
                            .addComponent(Talepurun))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Adres)
                            .addComponent(musterisoyadı)
                            .addComponent(musteriadı)
                            .addComponent(TalepUrun))))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(MusteriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriAdı))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MusteriSoyadi)
                    .addComponent(musterisoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adres)
                    .addComponent(Adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Talepurun)
                    .addComponent(TalepUrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(MusteriEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesajkutusu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteriadıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriadıActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_musteriadıActionPerformed

    private void MusteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriEkleActionPerformed
                   Islemler islemler = new Islemler();
                   String musteriAdı=musteriadı.getText();
                   String musteriSoyadı=musterisoyadı.getText();
                   String adres=Adres.getText();
                   String talepurun=TalepUrun.getText();
                   islemler.musteriEkle(musteriAdı, musteriSoyadı, adres,talepurun);
                   int deger;                         
                   deger = islemler.musteriEkle(musteriAdı, musteriSoyadı, adres, talepurun);
                   if(deger==1){
                       mesajkutusu.setText("Musteri Basarıyla Eklendi");
                   }
                   else if(deger==0){
                       
                      mesajkutusu.setText("Musteri Ekleme Başarısız!");
                      
                   }
    }//GEN-LAST:event_MusteriEkleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adres;
    private javax.swing.JButton MusteriEkle;
    private javax.swing.JLabel MusteriSoyadi;
    private javax.swing.JTextField TalepUrun;
    private javax.swing.JLabel Talepurun;
    private javax.swing.JLabel adres;
    private javax.swing.JLabel mesajkutusu;
    private javax.swing.JLabel musteriAdı;
    private javax.swing.JTextField musteriadı;
    private javax.swing.JTextField musterisoyadı;
    // End of variables declaration//GEN-END:variables
}
